apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  selector:
    env: deploy
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: jenkins-pvc


spec:
    accessModes:
    - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi


---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: jenkins
    labels:
      env: deploy 
spec:
  replicas: 1
  selector:
    matchLabels:
       env: deploy
  template:
    metadata:
     name: jenkins-pod
     labels:
       env: deploy
    spec: 
      containers:
        - name: jenkins
          image: aroraabhishek/docker-jenkins:v3
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-pvc
      